
# TODO: zahrnout do globálních rout > recipes.
#_fousky_tree:
#    resource: "@FouskyTreeBundle/Resources/config/routing.yml"
#    prefix:   /admin

fousky_tree_data:
    path:     /tree/data
    defaults:
        _controller: FouskyTreeBundle:TreeAdmin:treeData
